import os
from docx import Document

def writeContentToDoc(file_path, content):
    """
    Writes or appends content to a .docx file.
    If the file exists, appends content from a new page.
    
    :param file_path: Path to the .docx file.
    :param content: String or list of strings to write to the file.
    
    """
    # Create folder path if it doesn't exist
    folder = os.path.dirname(file_path)
    if folder and not os.path.exists(folder):
        os.makedirs(folder, exist_ok=True)
        
    # Check if file exists
    if os.path.exists(file_path):
        doc = Document(file_path)
        doc.add_page_break()  # Start new content on a new page
    else:
        doc = Document()
        # doc.add_heading('Document Generated by Script', level=1)
    
    # Add content
    if isinstance(content, list):
        for paragraph in content:
            doc.add_paragraph(paragraph)
    else:
        doc.add_paragraph(content)

    # Save the file
    doc.save(file_path)
    print(f"Content written/appended to: {file_path}")
