import os
import sys
from faster_whisper import WhisperModel

# This is a placeholder for your globalVariables module.
# In a real scenario, you would have this file.
class MockGlobalVariables:
    model_name = "base"
    device = "cuda"
    compute_type = "float16"
    font_name = "Arial"
    font_size = 28
    primary_color = "&H00FFFFFF&"
    highlight_color = "&H0000FFFF&" # Yellow for highlight
    outline_color = "&H00000000&"
    back_color = "&H64000000&"
    resolution = (1920, 1080)
    style_name = "WordPop"
    alignment = 5 # Middle center
    margin = (30, 30, 30)
    pop_duration_ms = 100
    zoom_font_size = 32

gv = MockGlobalVariables()

# This check prevents errors if the original globalVariables file doesn't exist
# when running this script standalone.
try:
    # Assuming globalVariables.py is in a path accessible by Python
    import globalVariables as gv
except ImportError:
    print("Warning: 'globalVariables.py' not found. Using default values.")
    pass


def format_ass_time(seconds):
    """Formats seconds into ASS time format (H:MM:SS.cs)."""
    hrs = int(seconds // 3600)
    mins = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    cs = int((seconds - int(seconds)) * 100)
    return f"{hrs}:{mins:02}:{secs:02}.{cs:02}"

def generateASSWithKaraoke(
    audioFilePath,
    outputASSPath,
    words_per_line=4, # <-- New parameter to control chunk size
    model_name=None,
    device=None,
    compute_type=None,
    font_name=None,
    font_size=None,
    primary_color=None,
    highlight_color=None,
    outline_color=None,
    back_color=None,
    resolution=None,
    style_name=None,
    alignment=None,
    margin=None,
    pop_duration_ms=None,
    zoom_font_size=None,
    margin_v=None
):
    """
    Generates ASS subtitles with word-level karaoke effects, chunked into
    lines of a specified word count to ensure precise timing and handling of silences.
    """
    # Set defaults from global variables if not provided
    model_name = model_name if model_name is not None else getattr(gv, 'model_name', "base")
    device = device if device is not None else getattr(gv, 'device', "cuda")
    compute_type = compute_type if compute_type is not None else getattr(gv, 'compute_type', "float16")
    font_name = font_name if font_name is not None else getattr(gv, 'font_name', "Arial")
    font_size = font_size if font_size is not None else getattr(gv, 'font_size', 28)
    primary_color = primary_color if primary_color is not None else getattr(gv, 'primary_color', "&H00FFFFFF&")
    highlight_color = highlight_color if highlight_color is not None else getattr(gv, 'highlight_color', "&H0000FFFF&")
    outline_color = outline_color if outline_color is not None else getattr(gv, 'outline_color', "&H00000000&")
    back_color = back_color if back_color is not None else getattr(gv, 'back_color', "&H64000000&")
    resolution = resolution if resolution is not None else getattr(gv, 'resolution', (1920, 1080))
    style_name = style_name if style_name is not None else getattr(gv, 'style_name', "WordPop")
    alignment = alignment if alignment is not None else getattr(gv, 'alignment', 5)
    margin = margin if margin is not None else getattr(gv, 'margin', (30, 30, 30))
    pop_duration_ms = pop_duration_ms if pop_duration_ms is not None else getattr(gv, 'pop_duration_ms', 100)
    zoom_font_size = zoom_font_size if zoom_font_size is not None else getattr(gv, 'zoom_font_size', 32)
    margin_v = margin_v if margin_v is not None else getattr(gv, 'margin_v', 580)

    print("Starting subtitle generation...")
    # Load Whisper model
    model = WhisperModel(model_name, device=device, compute_type=compute_type)
    
    print(f"Transcribing '{os.path.basename(audioFilePath)}' with word-level timestamps...")
    segments, _ = model.transcribe(audioFilePath, word_timestamps=True)

    playres_x, playres_y = resolution
    margin_l, margin_r, margin_v = margin

    with open(outputASSPath, "w", encoding="utf-8") as f:
        # --- ASS Header ---
        f.write("[Script Info]\n")
        f.write("Title: Generated by Gemini\n")
        f.write("ScriptType: v4.00+\n")
        f.write(f"PlayResX: {playres_x}\n")
        f.write(f"PlayResY: {playres_y}\n\n")

        # --- ASS Styles ---
        f.write("[V4+ Styles]\n")
        f.write("Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour,"
                " BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle,"
                " BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n")
        f.write(
            f"Style: {style_name},{font_name},{font_size},{primary_color},{highlight_color},"
            f"{outline_color},{back_color},-1,0,0,0,100,100,0,0,1,2,1,{alignment},"
            f"{margin_l},{margin_r},{margin_v},1\n\n"
        )

        # --- ASS Events ---
        f.write("[Events]\n")
        f.write("Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n")

        # --- CORE LOGIC CHANGE ---
        # 1. Flatten all words from all segments into a single list
        all_words = []
        for seg in segments:
            all_words.extend(seg.words)
            
        if not all_words:
            print("No words were transcribed. Output file will be empty.")
            return "No words found"

        # 2. Process the flat list of words in chunks
        current_pos = 0
        while current_pos < len(all_words):
            # Define the start and end of the chunk
            chunk_end_pos = min(current_pos + words_per_line, len(all_words))
            chunk_words = all_words[current_pos:chunk_end_pos]

            if not chunk_words:
                break

            # 3. Calculate precise start/end times for the chunk
            line_start_time = chunk_words[0].start
            line_end_time = chunk_words[-1].end
            
            # Format times for the ASS file
            start_text = format_ass_time(line_start_time)
            end_text = format_ass_time(line_end_time)

            dialogue_line = ""
            for word in chunk_words:
                # Calculate word start/end times relative to the LINE's start time
                word_start_ms = int((word.start - line_start_time) * 1000)
                word_end_ms = int((word.end - line_start_time) * 1000)
                
                clean_word = word.word.strip().replace('{', '').replace('}', '')

                # Karaoke effect tag for each word
                # This makes the word pop to a larger size and different color
                pop_tag = (
                    f"{{\\t({word_start_ms},{word_start_ms + pop_duration_ms},\\fscx120\\fscy120\\1c{highlight_color})}}"
                    f"{{\\t({word_end_ms},{word_end_ms + pop_duration_ms},\\fscx100\\fscy100\\1c{primary_color})}}"
                )
                dialogue_line += f"{pop_tag}{clean_word} "

            # Write the complete dialogue line for the chunk
            f.write(f"Dialogue: 0,{start_text},{end_text},{style_name},,0,0,0,,{dialogue_line.strip()}\n")

            # Move to the next chunk
            current_pos = chunk_end_pos

    print(f"ASS file creation completed: '{outputASSPath}'")
    return "Success"

# Example of how to run this function
if __name__ == '__main__':
    # Create a dummy audio file for testing if you don't have one.
    # This requires `ffmpeg` and `gtts` (pip install gtts)
    try:
        from gtts import gTTS
        dummy_audio_path = "test_story.mp3"
        if not os.path.exists(dummy_audio_path):
            print("Creating a dummy audio file 'test_story.mp3' for demonstration...")
            tts = gTTS("This is a short story. There will be a pause... and then the story continues.", lang='en')
            tts.save(dummy_audio_path)
            print("Dummy audio file created.")
    except ImportError:
        print("Skipping dummy audio creation. Please provide a real audio file.")
        dummy_audio_path = "path/to/your/audio.mp3" # IMPORTANT: Change this line
        
    output_ass_file = "word_pop_subtitles.ass"

    # --- FUNCTION CALL ---
    # You can now specify how many words you want per line.
    # Try changing words_per_line to 3 or 5 to see the difference.

    
    # generateASSWithKaraoke(
    #     audioFilePath=dummy_audio_path,
    #     outputASSPath=output_ass_file,
    #     words_per_line=4, 
    #     device="cpu", # Use "cpu" if you don't have a powerful GPU
    #     compute_type="int8" # Faster but less accurate, good for CPU
    # )
