import os
import sys
from faster_whisper import WhisperModel

# This is a placeholder for your globalVariables module.
# In a real scenario, you would have this file.
class MockGlobalVariables:
    model_name = "base"
    device = "cuda"
    compute_type = "float16"
    font_name = "Arial Black"
    font_size = 48
    primary_color = "&H00FFFFFF&" # White
    highlight_color = "&H0000FFFF&" # Yellow
    outline_color = "&H00000000&"
    back_color = "&H90000000&" # More opaque shadow for better readability
    resolution = (1080, 1920) # Vertical format like Reels/Shorts
    style_name = "DynamicCaption"
    alignment = 2 # Bottom center
    margin = (40, 40, 480)

gv = MockGlobalVariables()

try:
    import globalVariables as gv
except ImportError:
    print("Warning: 'globalVariables.py' not found. Using default values.")
    pass


def format_ass_time(seconds):
    """Formats seconds into ASS time format (H:MM:SS.cs)."""
    hrs = int(seconds // 3600)
    mins = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    cs = int((seconds - int(seconds)) * 100)
    return f"{hrs}:{mins:02}:{secs:02}.{cs:02}"

def generateASSWithKaraoke(
    audioFilePath,
    outputASSPath,
    words_per_line=3,
    animation_style="karaoke", # <-- New parameter for effects! "karaoke", "fade", "slide_up", "bounce", "punch"
    model_name=None,
    device=None,
    compute_type=None,
    font_name=None,
    font_size=None,
    primary_color=None,
    highlight_color=None,
    outline_color=None,
    back_color=None,
    resolution=None,
    style_name=None,
    alignment=None,
    margin=None
):
    """
    Generates ASS subtitles with various CapCut-style animations.
    Animation Styles: "karaoke", "fade", "slide_up", "bounce", "punch"
    """
    # Set defaults from global variables if not provided
    model_name = model_name if model_name is not None else getattr(gv, 'model_name', "base")
    device = device if device is not None else getattr(gv, 'device', "cuda")
    compute_type = compute_type if compute_type is not None else getattr(gv, 'compute_type', "float16")
    font_name = font_name if font_name is not None else getattr(gv, 'font_name', "Arial Black")
    font_size = font_size if font_size is not None else getattr(gv, 'font_size', 48)
    primary_color = primary_color if primary_color is not None else getattr(gv, 'primary_color', "&H00FFFFFF&")
    highlight_color = highlight_color if highlight_color is not None else getattr(gv, 'highlight_color', "&H0000FFFF&")
    outline_color = outline_color if outline_color is not None else getattr(gv, 'outline_color', "&H00000000&")
    back_color = back_color if back_color is not None else getattr(gv, 'back_color', "&H90000000&")
    resolution = resolution if resolution is not None else getattr(gv, 'resolution', (1080, 1920))
    style_name = style_name if style_name is not None else getattr(gv, 'style_name', "DynamicCaption")
    alignment = alignment if alignment is not None else getattr(gv, 'alignment', 2)
    margin = margin if margin is not None else getattr(gv, 'margin', (40, 40, 40))

    print(f"Starting subtitle generation with '{animation_style}' style...")
    model = WhisperModel(model_name, device=device, compute_type=compute_type)
    
    print(f"Transcribing '{os.path.basename(audioFilePath)}'...")
    segments, _ = model.transcribe(audioFilePath, word_timestamps=True)

    playres_x, playres_y = resolution
    margin_l, margin_r, margin_v = margin

    with open(outputASSPath, "w", encoding="utf-8") as f:
        # --- ASS Header & Styles ---
        f.write("[Script Info]\nTitle: Generated by Gemini\nScriptType: v4.00+\n")
        f.write(f"PlayResX: {playres_x}\nPlayResY: {playres_y}\nWrapStyle: 0\n\n")
        f.write("[V4+ Styles]\n")
        f.write("Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour,"
                " BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle,"
                " BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n")
        f.write(
            f"Style: {style_name},{font_name},{font_size},{primary_color},{highlight_color},"
            f"{outline_color},{back_color},-1,0,0,0,100,100,0,0,1,2,2,{alignment},"
            f"{margin_l},{margin_r},{margin_v},1\n\n"
        )
        f.write("[Events]\n")
        f.write("Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n")

        # --- CORE LOGIC ---
        all_words = [word for seg in segments for word in seg.words]
            
        if not all_words:
            print("No words were transcribed.")
            return "No words found"
        
        current_pos = 0
        while current_pos < len(all_words):
            chunk_words = []
            words_in_chunk = 0

            while current_pos < len(all_words):
                word = all_words[current_pos]
                chunk_words.append(word)
                words_in_chunk += 1

                word_text = word.word.strip()
                ends_with_pause = word_text[-1] in [".", ",", "!", "?", ":", ";", "…", "—"]

                # If pause found OR we hit the words_per_line limit, decide if we can end here
                if ends_with_pause or words_in_chunk >= words_per_line:
                    # If it doesn't end with a pause, check if the next word does
                    if not ends_with_pause and current_pos + 1 < len(all_words):
                        next_word = all_words[current_pos + 1]
                        next_text = next_word.word.strip()
                        next_ends_with_pause = next_text[-1] in [".", ",", "!", "?", ":", ";", "…", "—"]

                        # Only add the next word if it creates a natural break
                        if next_ends_with_pause:
                            chunk_words.append(next_word)
                            current_pos += 1
                    break  # Exit the inner loop: chunk is done

                current_pos += 1

            if not chunk_words:
                break  # No more words, safety net

            # Calculate timings for this chunk
            line_start_time = chunk_words[0].start
            line_end_time = chunk_words[-1].end
            start_text = format_ass_time(line_start_time)
            end_text = format_ass_time(line_end_time)

            # Build the dialogue line with per-word effects
            dialogue_line = ""
            for i, word in enumerate(chunk_words):
                word_start_ms = int((word.start - line_start_time) * 1000)
                word_duration_cs = int((word.end - word.start) * 100)  # For \K
                clean_word = word.word.strip().replace('{', '').replace('}', '')

                stagger_delay = i * 120  # Customize stagger as needed

                # Animation style selection (unchanged — reuse your original switch here)
                effect_tag = ""
                if animation_style == "karaoke":
                    effect_tag = f"{{\\K{word_duration_cs}}}"
                elif animation_style == "fade":
                    effect_tag = f"{{\\1c{primary_color}\\alpha&HFF&\\t({stagger_delay},{stagger_delay+300},\\alpha&H00)}}"
                elif animation_style == "slide_up":
                    effect_tag = (
                        f"{{\\an5\\1c{primary_color}\\pos(0,20)\\alpha&HFF&"
                        f"\\t({stagger_delay},{stagger_delay+400},\\pos(0,0))"
                        f"\\t({stagger_delay},{stagger_delay+300},\\alpha&H00)}}"
                    )
                elif animation_style == "bounce":
                    effect_tag = (
                        f"{{\\an5\\1c{highlight_color}\\fscx125\\fscy125\\alpha&HFF&"
                        f"\\t({stagger_delay},{stagger_delay+400},\\fscx100\\fscy100\\1c{primary_color}\\alpha&H00)}}"
                    )
                elif animation_style == "punch":
                    effect_tag = (
                        f"{{\\an5\\1c{primary_color}\\fscx120\\fscy120\\alpha&HFF&"
                        f"\\t({stagger_delay},{stagger_delay+300},\\fscx100\\fscy100\\alpha&H00)}}"
                    )
                else:
                    effect_tag = f"{{\\1c{highlight_color}}}"

                dialogue_line += f"{effect_tag}{clean_word} "

            f.write(f"Dialogue: 0,{start_text},{end_text},{style_name},,0,0,0,,{{\\r}}{dialogue_line.strip()}\n")

            current_pos += 1  # Move to the next word after the chunk


        
        

        
        
    #     current_pos = 0
    #     while current_pos < len(all_words):
    #         chunk_end_pos = min(current_pos + words_per_line, len(all_words))
    #         chunk_words = all_words[current_pos:chunk_end_pos]

    #         if not chunk_words: break

    #         line_start_time = chunk_words[0].start
    #         line_end_time = chunk_words[-1].end
    #         start_text = format_ass_time(line_start_time)
    #         end_text = format_ass_time(line_end_time)

    #         dialogue_line = ""
    #         for i, word in enumerate(chunk_words):
    #             word_start_ms = int((word.start - line_start_time) * 1000)
    #             word_duration_cs = int((word.end - word.start) * 100) # Duration in centiseconds for \K
                
    #             clean_word = word.word.strip().replace('{', '').replace('}', '')
                
    #             # --- ANIMATION STYLE SELECTION (Corrected and Improved) ---
    #             effect_tag = ""
    #             stagger_delay = i * 80 # Stagger animation for each word in a line

    #             if animation_style == "karaoke":
    #                 # Fills word with SecondaryColour. \K uses centiseconds.
    #                 effect_tag = f"{{\\K{word_duration_cs}}}"
                
    #             elif animation_style == "fade":
    #                 # Fades each word in.
    #                 effect_tag = f"{{\\1c{primary_color}\\alpha&HFF&\\t({stagger_delay}, {stagger_delay+300}, \\alpha&H00)}}"

    #             elif animation_style == "slide_up":
    #                 # BUG FIX: Replaced invalid \fad with \t(\alpha) transform.
    #                 # Slides each word up and fades it in.
    #                 effect_tag = (
    #                     f"{{\\an5\\1c{primary_color}\\pos(0,20)\\alpha&HFF&" # Initial state: moved down, transparent
    #                     f"\\t({stagger_delay}, {stagger_delay+400}, \\pos(0,0))" # Animate position
    #                     f"\\t({stagger_delay}, {stagger_delay+300}, \\alpha&H00)}}" # Animate alpha
    #                 )
                
    #             elif animation_style == "bounce":
    #                 # Bounces in size and changes color temporarily. More robust now.
    #                 effect_tag = (
    #                     f"{{\\an5\\1c{highlight_color}\\fscx125\\fscy125\\alpha&HFF&" # Initial state
    #                     f"\\t({stagger_delay}, {stagger_delay+400}, \\fscx100\\fscy100\\1c{primary_color}\\alpha&H00)}}"
    #                 )
                
    #             elif animation_style == "punch":
    #                 # NEW STYLE: Starts bigger and transparent, then scales down and fades in.
    #                 effect_tag = (
    #                     f"{{\\an5\\1c{primary_color}\\fscx120\\fscy120\\alpha&HFF&" # Initial state
    #                     f"\\t({stagger_delay}, {stagger_delay+300}, \\fscx100\\fscy100\\alpha&H00)}}"
    #                 )

    #             else: # Default to a simple highlight if style is unknown
    #                  effect_tag = f"{{\\1c{highlight_color}}}"

    #             dialogue_line += f"{effect_tag}{clean_word} "

    #         # The {\r} tag resets the style for the line.
    #         f.write(f"Dialogue: 0,{start_text},{end_text},{style_name},,0,0,0,,{{\\r}}{dialogue_line.strip()}\n")

    #         current_pos = chunk_end_pos

    # print(f"ASS file creation completed: '{outputASSPath}'")
    # return "Success"